FROM wilder/minecraft-bedrock:1.16.220.01

ENV CORE_VERSION "1.16.220.01"
#ENV SERVER_PATH /mcpe/server
#ENV SCRIPT_PATH /mcpe/script
#ENV DATA_PATH /data

RUN apt-get update \
	&& apt install -y vim screen procps file \
	&& apt-get -y autoremove && apt-get clean

# Add custom profile.d files (these don't run for some reason)
COPY config/profile/aliases.sh /etc/profile.d/aliases.sh
COPY config/profile/aliases.sh /etc/profile.d/aliases.bash
RUN chmod +x /etc/profile.d/*.sh /etc/profile.d/*.bash
RUN . /etc/profile.d/aliases.sh

# Add custom entrypoint script to enable development
COPY config/script/docker-entrypoint__with-screen.sh ${SCRIPT_PATH}/docker-entrypoint-nodev.sh
COPY config/script/docker-entrypoint-dev__mod__with-screen.sh ${SCRIPT_PATH}/docker-entrypoint-dev.sh
COPY config/script/docker-entrypoint-dev__mod__with-screen.sh ${SCRIPT_PATH}/docker-entrypoint.sh
RUN chmod +x ${SCRIPT_PATH}/*.sh

# Redefining entrypoint for custom dev environment
# cwilder: comments out the following lines b/c overriding the "docker-entrypoint.sh" is a cleaner solution. 
#ENTRYPOINT ["${SCRIPT_PATH}/docker-entrypoint.sh"]
#CMD ["${SCRIPT_PATH}/start-dev.sh"]

#ENTRYPOINT ["/mcpe/script/docker-entrypoint.sh", "/mcpe/server/bedrock_server"]
#ENTRYPOINT ["/mcpe/script/docker-entrypoint.sh"]
#CMD ["/mcpe/server/bedrock_server"]
CMD ["/mcpe/script/docker-entrypoint.sh", "/mcpe/server/bedrock_server"]