version: '3'

services:
   mcpe: # container name
      build: .
      image: minecraft-bedrock:latest
      ports:
         - 19132:19132/udp
      volumes:
         - /opt/mcpe-data:/data
      restart: always
      stdin_open: true
      tty: true
