version: '3'

services:
   mcpe:
      container_name: mcpe
      image: wilder/minecraft-bedrock:1.16.220.01
      ports:
         - 19132:19132/udp
      volumes:
         - /opt/mcpe-data:/data
      restart: always
      stdin_open: true
      tty: true
