name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.DOCKER_ID }} --password=${{ secrets.DOCKER_TOKEN }}
        docker build . --file Dockerfile --tag lomot/minecraft-bedrock:latest
    - name: upload image
      run: |
        docker tag lomot/minecraft-bedrock:latest lomot/minecraft-bedrock:dev
        docker push lomot/minecraft-bedrock:dev
