name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag lomot/minecraft-bedrock:latest
    - name: upload image
      run: |
        CORE_VERSION=$(cat Dockerfile | grep "CORE_VERSION=" | cut -f2 -d \")
        docker login --username=${{ secrets.DOCKER_ID }} --password=${{ secrets.DOCKER_TOKEN }}
        docker tag lomot/minecraft-bedrock:latest lomot/minecraft-bedrock:$CORE_VERSION
        docker push lomot/minecraft-bedrock:latest
        docker push lomot/minecraft-bedrock:$CORE_VERSION
