name: OnTags

on:
  push:
    tags:
      - 1.*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Set meta data
      id: meta
      run: echo ::set-output name=tag::${GITHUB_REF:10}

    - name: Build image
      run: |
        docker build . --file Dockerfile --tag lomot/minecraft-bedrock:latest

    - name: Upload image
      env:
        RELEASE_VERSION: ${{ steps.meta.outputs.tag }}
      run: |
        CORE_VERSION=$(cat Dockerfile | grep "CORE_VERSION=" | cut -f2 -d \")
        docker login --username=${{ secrets.DOCKER_ID }} --password=${{ secrets.DOCKER_TOKEN }}
        docker tag lomot/minecraft-bedrock:latest lomot/minecraft-bedrock:${{ env.RELEASE_VERSION }}
        docker push lomot/minecraft-bedrock:${{ env.RELEASE_VERSION }}
        # echo "RELEASE_VERSION:" ${{ env.RELEASE_VERSION }}
        # echo "RELEASE_VERSION2:" ${RELEASE_VERSION }

